import type { Metadata } from 'next'
import localFont from "next/font/local";
import './globals.css'

const brownRegular = localFont({
  src: "./fonts/Brown-Regular.woff2",
  variable: "--font-brown-regular",
  weight: "400",
});
const brownBold = localFont({
  src: "./fonts/Brown-Bold.woff2",
  variable: "--font-brown-bold",
  weight: "700",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={`${brownRegular.variable} ${brownBold.variable}`}>
      {children}
    </body>
    </html>
  )
}
